# install_services.yml

---
  - hosts: lb
    become: true
    tasks:
      - name: Install Services
        yum: name=httpd state=present
      - name: Starts Apache
        service: name=httpd state=started enabled=yes
  - hosts: web
    become: true
    tasks:
      - name: Installing services
        yum:
          name:
            - httpd
            - php
          state: present
      - name: Starts Apache  
        service: name=httpd state=started enabled=yes
  - hosts: docker
    name: "AmazonLinux Install Docker"
    become: yes
    tasks:
      - name: Update all packages
        yum:
          name: '*'
          state: latest
          # update_only: yes

      - name: Ensure a list of yum packages are installed
        yum:
          name: "{{ packages }}"
          state: present
          update_cache: yes
        vars:
          packages:
          - python-pip
          - yum-utils
          - device-mapper-persistent-data
          - lvm2
          - amazon-linux-extras
      - name: Add extras repository
        shell: yum-config-manager --enable extras
        # state: present
      - name: Install docker-ce (centos) via amazon-linux-extras packages
        shell: "amazon-linux-extras install docker=18.06.1 -y"
        # state: present

      - name: Enable Docker CE service at startup
        service:
          name: docker
          state: started
          enabled: yes
      - name: Modify privilege
        become: true
        shell: usermod -aG docker ec2-user

      - name: Ensure Python pip packages are installed
        pip:
          name: "{{ packages }}"
        vars:
          packages:
          - boto
          - boto3
          - docker-compose
  # - hosts: docker_ubuntu           
  #   tasks:
  #   - name: Install prerequisites
  #     become: true
  #     apt:
  #       name: "{{ packages }}"
  #       state: present
  #       update_cache: yes
  #     vars:
  #       packages:
  #       - apt-transport-https
  #       - ca-certificates
  #       - curl
  #       - gnupg2
  #       - software-properties-common

  #   - name: Add Docker GPG key
  #     become: true
  #     apt_key: url=https://download.docker.com/linux/ubuntu/gpg

  #   - name: Add Docker APT repository
  #     become: true
  #     apt_repository:
  #       repo: deb [arch=amd64] https://download.docker.com/linux/{{ansible_distribution|lower}} {{ansible_distribution_release}} stable

  #   - name: Install Docker
  #     become: true
  #     apt:
  #       name: "{{ packages }}"
  #       state: present
  #     vars:
  #       packages:
  #       - docker-ce
  #       - docker-ce-cli
  #       - containerd.io
  #   - name: Install Docker-compose
  #     become: true
  #     # shell: curl -L "https://github.com/docker/compose/releases/download/1.24.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
  #     get_url:
  #       url: "https://github.com/docker/compose/releases/download/1.24.0/docker-compose-{{ansible_system}}-{{ansible_architecture}}"
  #       dest: /usr/local/bin/docker-compose
  #       mode: +x