# setup_app.yml

---
  - hosts: web
    become: true
    vars_files: 
      - ../secrets.yml
    tasks:
      - name: Use Secret Password Here
        debug:
          msg: "{{ secret_password }}"
      - name: Uploads php file
        copy:
          src: ../index.php 
          dest: /var/www/html
          mode: 0755
      - name: Configure php.ini file
        lineinfile:
          path: /etc/php.ini
          regexp: ^short_open_tag
          line: 'short_open_tag=On'
      - name: Restart apache
        service: name=httpd state=restarted